---
name: CompatHelper
on:
  schedule:
    - cron: "0 0 * * *"  # Everyday at midnight
  workflow_dispatch: {}
jobs:
  CompatHelper:
    runs-on: ubuntu-slim
    steps:
      - name: Install CompatHelper
        shell: julia --color=yes --project=@compathelper {0}
        run: |
          using Pkg
          Pkg.add("CompatHelper")
      - name: Run CompatHelper
        shell: julia --color=yes -project=@compathelper {0}
          using CompatHelper
          CompatHelper.main()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMPATHELPER_PRIV: ${{ secrets.DOCUMENTER_KEY }}
